"""empty message

Revision ID: e45c9f51b008
Revises: 
Create Date: 2019-04-26 22:27:44.903605

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e45c9f51b008'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('purchase_agent',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.Column('mobile', sa.String(length=15), nullable=False),
    sa.Column('address', sa.String(length=200), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name', 'mobile', name='_name_mobile_uc')
    )
    op.create_index(op.f('ix_purchase_agent_mobile'), 'purchase_agent', ['mobile'], unique=False)
    op.create_index(op.f('ix_purchase_agent_name'), 'purchase_agent', ['name'], unique=False)
    op.create_table('roles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('sale_agent',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.Column('mobile', sa.String(length=15), nullable=False),
    sa.Column('address', sa.String(length=200), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name', 'mobile', name='_name_mobile_uc')
    )
    op.create_index(op.f('ix_sale_agent_mobile'), 'sale_agent', ['mobile'], unique=False)
    op.create_index(op.f('ix_sale_agent_name'), 'sale_agent', ['name'], unique=False)
    op.create_table('varieties',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('purchases',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('rstnumber', sa.Float(), nullable=False),
    sa.Column('weight', sa.Float(), nullable=False),
    sa.Column('moisture', sa.Float(), nullable=False),
    sa.Column('rate', sa.Float(), nullable=False),
    sa.Column('variety_id', sa.String(length=64), nullable=False),
    sa.Column('agent_id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['agent_id'], ['purchase_agent.id'], ),
    sa.ForeignKeyConstraint(['variety_id'], ['varieties.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_purchases_timestamp'), 'purchases', ['timestamp'], unique=False)
    op.create_table('sales',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('party_name', sa.String(length=128), nullable=False),
    sa.Column('party_address', sa.String(length=200), nullable=False),
    sa.Column('gst_number', sa.String(length=32), nullable=False),
    sa.Column('vehicle_number', sa.String(length=32), nullable=False),
    sa.Column('no_of_bags', sa.Integer(), nullable=False),
    sa.Column('variety_id', sa.String(length=64), nullable=False),
    sa.Column('agent_id', sa.Integer(), nullable=False),
    sa.Column('quintol', sa.Float(), nullable=False),
    sa.Column('rate', sa.Float(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['agent_id'], ['sale_agent.id'], ),
    sa.ForeignKeyConstraint(['variety_id'], ['varieties.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sales_timestamp'), 'sales', ['timestamp'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=True),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.Column('password_hash', sa.String(length=128), nullable=True),
    sa.Column('role_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_sales_timestamp'), table_name='sales')
    op.drop_table('sales')
    op.drop_index(op.f('ix_purchases_timestamp'), table_name='purchases')
    op.drop_table('purchases')
    op.drop_table('varieties')
    op.drop_index(op.f('ix_sale_agent_name'), table_name='sale_agent')
    op.drop_index(op.f('ix_sale_agent_mobile'), table_name='sale_agent')
    op.drop_table('sale_agent')
    op.drop_table('roles')
    op.drop_index(op.f('ix_purchase_agent_name'), table_name='purchase_agent')
    op.drop_index(op.f('ix_purchase_agent_mobile'), table_name='purchase_agent')
    op.drop_table('purchase_agent')
    # ### end Alembic commands ###
